---
tardis_config_version: v1.0
supernova:
    luminosity_requested: 8.754 log_lsun
    time_explosion: 14 day
atom_data: kurucz_cd23_chianti_H_He.h5
model:
    structure:
        type: file
        filename: tardis_sn2005bl_m3_density.dat
        filetype: simple_ascii
        v_inner_boundary: 7.5e3 km/s
        v_outer_boundary : 30000 km/s
    abundances:
        type: file
        filename: tardis_sn2005bl_m3_abundances.dat
        filetype: simple_ascii
plasma:
    disable_electron_scattering: no
    ionization: nebular
    excitation: dilute-lte
    radiative_rates_type: dilute-blackbody
    line_interaction_type: downbranch
montecarlo:
    seed: 23111963
    no_of_packets : 4.0e+4
    iterations: 20
    last_no_of_packets: 1.e+5
    no_of_virtual_packets: 10
    convergence_strategy:
        type: damped
        damping_constant: 1.0
        threshold: 0.05
        fraction: 0.8
        hold_iterations: 3
        t_inner:
            damping_constant: 1.0
spectrum:
    start : 500 angstrom
    stop : 20000 angstrom
    num: 10000
